const BAIRROS_IA = [

    "Alto Aririú",
    "Albardão",
    "Área Rural de Palhoça",
    "Aririú",
    "Aririú da Formiga",
    "Balneário Ponta do Papagaio",
    "Barra do Aririú",
    "Bela Vista",
    "Brejarú",
    "Caminho Novo",
    "Centro",
    "Enseada do Brito",
    "Furadinho",
    "Guarda do Cubatão",
    "Guarda do Embaú",
    "Jardim Aquarius",
    "Jardim Coqueiros",
    "Jardim das Palmeiras",
    "Jardim Eldorado",
    "Madri",
    "Massiambu Pequeno",
    "Morretes",
    "Nova Palhoça",
    "Pachecos",
    "Pagani",
    "Passa Vinte",
    "Passagem do Massiambú",
    "Pedra Branca",
    "Pinheira",
    "Ponte do Imaruim",
    "Praia de Fora",
    "Praia do Meio",
    "Praia do Pontal",
    "Praia do Sonho",
    "Rio Grande",
    "São Sebastião",
    "Sertão do Campo",
    "Três Barras"

];