const RUAS_IA = [

    "Alça de Acesso",
    "Avenida Amoritas",
    "Avenida Cananeus",
    "Avenida Central Firenze",
    "Avenida das Civilizações",
    "Avenida do Comércio",
    "Avenida dos Continentes",
    "Avenida Norte-Sul",
    "Rodovia BR-101",
    "Rua 1ª Transversal Firenze",
    "Rua 2ª Transversal Firenze",
    "Rua 3ª Transversal Firenze",
    "Rua Adelina Julia de Campos",
    "Rua Alaíde Linhares Macedo",
    "Rua Alzerino Francisco Velho",
    "Rua Antonio Benjamim Batista",
    "Rua Antonio da Bicota",
    "Rua Antônio Braz Damazio",
    "Rua Arcadianos",
    "Rua Ari Bernardino Coelho",
    "Rua Artur Sell",
    "Rua Astecas",
    "Rua Braulino Gutiha",
    "Rua Bento Manoel Dutra",
    "Rua Celtas",
    "Rua Célio Velho",
    "Rua Crescêncio Inácio da Silva",
    "Rua do Juca",
    "Rua Dorvalina Maria da Silva",
    "Rua Egito",
    "Rua Elizabete Czechoski Mendes",
    "Rua Fenícios",
    "Rua Francisco Velho",
    "Rua Gregos",
    "Rua Inácio Paulo Dalri",
    "Rua Inca",
    "Rua Januário Pereira de Lima",
    "Rua João Antônio da Silva",
    "Rua João Clemente Botelho",
    "Rua João Domingos da Silva",
    "Rua João Gualberto Gonçalves",
    "Rua João Martins de Souza",
    "Rua José Cândido da Silva",
    "Rua José Duarte da Silva",
    "Rua José Paulo Esteves Ávila",
    "Rua Lauri Antonio da Silva",
    "Rua Maias",
    "Rua Manoel Pacheco da Silva",
    "Rua Maria José da Conceição",
    "Rua Maria Leopoldina da Silva",
    "Rua Natalino Campos Schaimann",
    "Rua Nelson Floriano Campos",
    "Rua Nova Iguaçu",
    "Rua Ondina Ana da Silva",
    "Rua Osni José Pereira",
    "Rua Osny Rogério Berreta",
    "Rua Persa",
    "Rua Recanto das Flores",
    "Rua Roberto Manoel Marques",
    "Rua Romanos",
    "Rua São Pedro",
    "Rua Sérgio Murilo de Pinho",
    "Rua Silvano Francisco da Silva",
    "Rua Vânio Pedro Dutra",
    "Rua Vasco e Macedo",
    "Rua Vikings",
    "Servidão Cília Bernardina de Quadros",
    "Servidão Diomar Boeing",
    "Servidão Edgar José Soares",
    "Servidão Edson João da Silva",
    "Servidão Elisa Caetana da Silva",
    "Servidão João Cândido da Silva Filho",
    "Servidão João Pedro Cristiano",
    "Servidão João Zeferino de Melo",
    "Servidão Manoel Cândido Borges",
    "Servidão Mauro Ramos",
    "Servidão Nelci Dias",
    "Servidão Pedro Antônio da Silva",
    "Servidão Roldão Serafim da Rosa",
    "Servidão Silvano Francisco da Silva",
    "Travessa Antonio Benjamim Batista",
    "Alameda dos Ipês",
    "Avenida Aniceto Zacchi",
    "Avenida Cláudio Osmar Silva",
    "Avenida Elza Lucchi",
    "Comunidade Urbana Ponte do Imaruim - Praia",
    "Rodovia BR-101",
    "Rua Acácio Santiago",
    "Rua Adolfo Ziguelli",
    "Rua Afonso Della Rocca",
    "Rua Albertina de Moraes",
    "Rua Alberto Guilherme Schlichting",
    "Rua Alberto Zluhan",
    "Rua Alcino Honório de Amorim",
    "Rua Alferes Tiradentes",
    "Rua Almirante Tamandaré",
    "Rua Altino José da Cunha",
    "Rua Ambrósio Alzemiro dos Santos",
    "Rua Aníbal Nunes Pires",
    "Rua Anita Garibaldi",
    "Rua Antônio Clemente Veber",
    "Rua Antônio Gonçalves Chaves",
    "Rua Antônio Muniz de Aragão",
    "Rua Antônio Vieira",
    "Rua Ari Alécio de Mello",
    "Rua Arlindo Alcebíades de Andrade",
    "Rua Armando Siegel",
    "Rua Armando Zacchi",
    "Rua Artur Osório de Araújo",
    "Rua Ataíde Pereira dos Anjos",
    "Rua Augusto Westphal",
    "Rua Basílio Albino Ramos Filho",
    "Rua Beira Rio-mar",
    "Rua Belmiro Della Justina",
    "Rua Calirio Ferreira",
    "Rua Capistrano",
    "Rua Carlos Alberto Campos",
    "Rua Cecília Meireles",
    "Rua Cláudio Coutinho",
    "Rua Claudomiro Pizani",
    "Rua Darci José Moreira",
    "Rua das Rosas",
    "Rua Dom Pedro II",
    "Rua Doralice Santana",
    "Rua Dorothea Olinda Schlemper",
    "Rua Emília Knabben da Silveira",
    "Rua Euclides da Cunha",
    "Rua Floriano Peixoto",
    "Rua Frederico Derci Feldberg",
    "Rua Frederico Wagner",
    "Rua Frei Elpídio",
    "Rua Frei João Vicelli",
    "Rua Frei Lauro",
    "Rua Frida Kohl Zluhan",
    "Rua Geraldo Jansen",
    "Rua Graciliano Ramos",
    "Rua Guarujá do Sul",
    "Rua Heitor Nunes",
    "Rua Hercílio Luz",
    "Rua Honório Cardoso",
    "Rua Israel Xavier Neves",
    "Rua Ivo Westphal",
    "Rua Jerônimo Ávila",
    "Rua João Aldoff",
    "Rua João Antônio dos Santos",
    "Rua João Batista Pierre",
    "Rua João Born",
    "Rua João Dias dos Santos",
    "Rua João Febrônio de Oliveira",
    "Rua João Gonçalves",
    "Rua João Odimar dos Santos",
    "Rua João Pereira de Medeiros",
    "Rua João Pereira dos Santos",
    "Rua Joaquim Souza Lobo",
    "Rua Jornalista Bento Silvério",
    "Rua José Adão",
    "Rua José Frederico Guedert",
    "Rua José Olibio Lopes",
    "Rua José Porto dos Santos",
    "Rua José Salvador Diniz",
    "Rua José Silveira de Souza",
    "Rua José Soares de Oliveira",
    "Rua José Soares de Oliveira (Clique e Retire Correios – nº 650)",
    "Rua Lázaro Bartolomeu",
    "Rua Lolita Philippe",
    "Rua Maiza Matarazzo",
    "Rua Major José Honório da Costa",
    "Rua Manoel Luiz Teixeira",
    "Rua Maracanã",
    "Rua Márcia de Winderson",
    "Rua Maria do Carmo Lopes",
    "Rua Maria Soares",
    "Rua Mário Rocha",
    "Rua Max Schlemper",
    "Servidão José Soares",
    "Servidão Jovenal dos Passos",
    "Servidão Maria Ramos",
    "Servidão Miletino da Rosa",
    "Servidão Peres",
    "Servidão Pierri",
    "Servidão Silva",
    "Servidão Silveira",
    "Servidão Souza",
    "Travessa Dolida",
    "Travessa José Manoel Marcelino",

    "Avenida Ari Amâncio da Silveira",
    "Avenida Beira Mar Sol",
    "Avenida Praia Sol",
    "Rua Altamiro Pereira de Lima",
    "Rua Alves de Souza",
    "Rua Amâncio Manoel Silveira",
    "Rua Amaro Serafim dos Passos",
    "Rua Anga Verde",
    "Rua Antonieta Corrêa",
    "Rua Antônio Júlio Fagundes",
    "Rua Arcanjo Cândido da Silva",
    "Rua B (Loteamento Chalé)",
    "Rua Belo Horizonte",
    "Rua Benta Martins Ribeiro",
    "Rua Bernardino Virgílio de Abreu",
    "Rua Bom Pastor",
    "Rua Brasília",
    "Rua C (Loteamento Marivone)",
    "Rua Campo Grande",
    "Rua Carlos Brito",
    "Rua Carlos Deolindo Dutra",
    "Rua Comandante Osni Schuttel Furtado",
    "Rua Coqueiros",
    "Rua Curitiba",
    "Rua Delorme Mazola",
    "Rua do Cedro",
    "Rua do Chalé",
    "Rua Dona Chica",
    "Rua Dona Ivone",
    "Rua Dona Júlia",
    "Rua dos Artistas",
    "Rua Elicio Nunes",
    "Rua Euclides Machado",
    "Rua Flores",
    "Rua Fortaleza",
    "Rua Garoupa",
    "Rua Genoino Pereira da Silva",
    "Rua Girassol",
    "Rua Goiânia",
    "Rua H (Loteamento Marivone)",
    "Rua Iguaçu",
    "Rua Ilha Bela",
    "Rua Ipê Amarelo",
    "Rua Itapema",
    "Rua Itapoá",
    "Rua J (Loteamento Marivone)",
    "Rua Jacarandá",
    "Rua João Alexandrino de Souza",
    "Rua João Batista Pires",
    "Rua João Born",
    "Rua João José da Silva",
    "Rua João Manoel de Souza",
    "Rua João Silveira",
    "Rua José Amaro da Silva",
    "Rua José Domingos de Oliveira",
    "Rua José Emídio de Souza",
    "Rua José Francisco de Souza",
    "Rua José Laurentino da Silva",
    "Rua José Manoel da Luz",
    "Rua José Maria da Luz",
    "Rua José Pedro de Souza",
    "Rua Júlio Cardoso",
    "Rua Lages",
    "Rua Laguna",
    "Rua Luiz Carlos Prestes",
    "Rua Manoel Bernardo da Rosa",
    "Rua Manoel de Souza",
    "Rua Maria Clara da Silva",
    "Rua Maria de Lourdes da Silva",
    "Rua Maria Rita da Silva",
    "Rua Navegantes",
    "Rua Nereu Ramos",
    "Rua Nova Esperança",
    "Rua Osni Schmitt",
    "Rua Otacílio Costa",
    "Rua Palmas",
    "Rua Paraná",
    "Rua Pescador",
    "Rua Porto Alegre",
    "Rua Recife",

    "Rua Maria Ignácia Fagundes",
    "Rua Maria Luiza de Abreu",
    "Rua Maria Rosa",
    "Rua Martinho Furlanetto",
    "Rua Maceió",
    "Rua Manoel da Silveira",
    "Rua Manoel da Silveira Dutra",
    "Rua Manoel Eufrásio de Medeiros",
    "Rua Moacir Fernandes",
    "Rua Monte Cambirela",
    "Rua Natal",
    "Rua Nicolau José Rozar",
    "Rua Olinda Olídia Vieira",
    "Rua Orquídeas",
    "Rua Oscar Martinho Ribeiro",
    "Rua Otávio João Rachadel",
    "Rua Pedra Branca",
    "Rua Porto Alegre",
    "Rua Querino Henrique da Silva",
    "Rua Raul Leonardo Weiss",
    "Rua Recife",
    "Rua Regina Caetana da Silveira",
    "Rua Rio de Janeiro",
    "Rua Sabiá",
    "Rua Salvador",
    "Rua São José",
    "Rua São Paulo",
    "Rua Tereza Carolina Fernandes",
    "Rua Valmir Ascari Castelano",
    "Rua Velho Leão do Mar",
    "Rua Vereador Bernardino Manoel Machado",
    "Rua Vereador Joaquim Serafim Dutra",
    "Rua Vereador José Joaquim Garcia",
    "Rua Vitório Beltrame",
    "Rua Walmor Wagner",
    "Rua Walmor Schütz",

    "Servidão Amilton Gonçalves",
    "Servidão Cantinho do Pescador",
    "Servidão do João Manoel da Rocha",
    "Servidão Ivonei Floriano",
    "Servidão Izolde Guckert Campos",
    "Servidão João Agostinho Heller",
    "Servidão João da Costa Barbosa",
    "Servidão João Venceslau dos Santos",
    "Servidão Ladislau Jaime Martins",
    "Servidão Manoel Vicente dos Passos",
    "Servidão Maria da Praia",
    "Servidão Martimiano Manoel Martins",
    "Servidão Maura da Silva Homem",
    "Servidão Mello",
    "Servidão Maria Flor",
    "Servidão Rosa Branca",
    "Servidão Savedra",

    "Rua 88130-542",
    "Rua 88130-414",

    "Avenida Caravelas",
    "Avenida Nova Aurora",
    "Avenida Panorama",
    "Avenida Radiante",
    "Comunidade Urbana Passagem do Maciambu",
    "Rodovia Evádio Paulo Broering",
    "Rua Acarai",
    "Rua Andaia",
    "Rua Andira",
    "Rua Araxá",
    "Rua Atalaia",
    "Rua Atalanta",
    "Rua Cambará",
    "Rua Cananéia",
    "Rua Canindé",
    "Rua Celso Francisco Garcia",
    "Rua Claudio Steinmetz",
    "Rua Clevelândia",
    "Rua Creta",
    "Rua Cuba",
    "Rua das Roseiras",
    "Rua Doze de Setembro",
    "Rua Doraci Pedro Pereira",
    "Rua Elizabete Souza",
    "Rua Gregória Matildes Martins",
    "Rua Guaciara",
    "Rua Guarapari",
    "Rua Guararema",
    "Rua Hilda Siegel Steinmetz",
    "Rua Iguape",
    "Rua Ijui",
    "Rua Ipanema",
    "Rua Ipoema",
    "Rua Ipoméia",
    "Rua Iporanga",
    "Rua Iracema",
    "Rua Itabira",
    "Rua Itacolomi",
    "Rua Itajaí",
    "Rua Itamaracá",
    "Rua Itambé",
    "Rua Itanhaém",
    "Rua Itapiranga",
    "Rua Itararé",
    "Rua Itatiaia",
    "Rua Itu",
    "Rua Jaciara",
    "Rua Jacupiranga",
    "Rua Jandaia",
    "Rua Jangada",
    "Rua Jataí",
    "Rua Jatobá",
    "Rua Juriti",
    "Rua Mar Azul",
    "Rua Mar Del Plata",
    "Rua Mar dos Açores",
    "Rua Marfim",
    "Rua Miraguaia",
    "Rua Monte Pascoal",
    "Rua Mucuri",
    "Rua Navegantes",
    "Rua Netuno",
    "Rua Norberto José de Souza",
    "Rua Onda Azul",
    "Rua Palmeiras",
    "Rua Paraíso",
    "Rua Pôr do Sol",
    "Rua Praia Bela",
    "Rua Primavera",
    "Rua Recanto do Sol",
    "Rua Rio Negro",
    "Rua Rosas do Sul",
    "Rua Santa Helena",
    "Rua Santa Maria",
    "Rua Santiago",
    "Rua Sol Nascente",
    "Rua Timbó",
    "Rua Tupã",
    "Rua Uruguai",
    "Rua Valdir dos Santos",
    "Rua Veneza",
    "Rua Vitória",
    "Rua Xangri-lá",
    "Rua Xavantes",

    "Servidão Plascindino Brasiliano dos Santos",
    "Rua Expedicionário Aderbal Correa da Silva",
    "Servidão Maria Laurinda",
    "Rua Tomáz Domingos da Silveira (de 2834/2835 ao fim)",
    "Rua Rosa",
    "Rua Norberto José Coelho",
    "Rua Ernesto Albino",
    "Rua Marlene Maria da Silva",
    "Rua Sérgio Luiz da Silva",
    "Rua Avelino Hillesheim",
    "Rua Ademir da Silva",
    "Rua Laurentina Arminda Miguel",
    "Rua Pedro Jovino de Souza",
    "Rua João Norato Miguel",
    "Rua Helena Shmtiz da Silva",
    "Rua André Felipe Filho Sumar",
    "Rua Jaldir João Steinbach",
    "Rua Luiz Silva",
    "Rua Ivo João Steinbach",
    "Rua Altino Martins",
    "Rua Rosalina Prim Steinbach",
    "Rua Gramado",
    "Rua Jaime Silveira de Souza",
    "Rua Cruz Alta",
    "Servidão João Marcelino Batista",
    "Servidão Gercino Ramos",
    "Rua Nelson Coelho",
    "Rua Samuel de Souza",
    "Rua Canaã",
    "Servidão Passos",
    "Servidão Maria dos Santos Ramos",
    "Servidão Soares",
    "Servidão Geraldo Vieira do Amaral",
    "Rua Zélia Maria dos Santos",
    "Rua Nelson Gonçalves",
    "Rua das Palmeiras",
    "Rua Emilia Filomena de Jesus",
    "Rua João Fredolino Dias",
    "Rua Arnoldo Ferreira",
    "Rua Osni José de Souza",
    "Rua Maurílio Artur dos Santos",
    "Rua João Antônio Vieira",
    "Rua Bento Gonçalves",
    "Rua José Bernardino de Lima",
    "Rua Manoel Duarte",
    "Servidão Caetana Emília Breis",
    "Rua Maria Martinho da Silva",
    "Servidão Robson Fraga",
    "Rua Paulo Manoel da Silva",
    "Rua Goiás"

];